apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app: {{ include "..fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "..fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "..fullname" . }}
        sidecar.istio.io/inject: "{{ .Values.istio.inject }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: "POSTGRES_HOST"
              value: "{{ .Values.postgres.host }}"
            - name: "POSTGRES_PORT"
              value: "{{ .Values.postgres.port }}"
            - name: "POSTGRES_DATABASE"
              value: "{{ .Values.postgres.database }}"
            - name: "POSTGRES_USERNAME"
              value: "{{ .Values.postgres.username }}"
            - name: "POSTGRES_PASSWORD"
              value: "{{ .Values.postgres.password }}"
            - name: "KAFKA_BROKERS"
              value: "{{ .Values.kafka.brokers }}"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.environment }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 20s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
